# Generated by Django 4.2.2 on 2024-01-17 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coming_id', models.IntegerField(verbose_name='coming_id')),
                ('category_id', models.IntegerField(verbose_name='category_id')),
                ('category', models.CharField(max_length=128, verbose_name='category_title')),
                ('title', models.CharField(max_length=255, verbose_name='catalog_title')),
                ('details', models.TextField(blank=True, null=True, verbose_name='catalog_details')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('unit', models.CharField(max_length=32, verbose_name='unit')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='catalog_photo')),
                ('storage', models.CharField(max_length=96, verbose_name='storage')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='total')),
                ('sale_quantity', models.IntegerField(verbose_name='sale_quantity')),
                ('available', models.IntegerField(verbose_name='available')),
            ],
            options={
                'db_table': 'view_catalog',
                'ordering': ['title'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewComing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datec', models.DateTimeField(verbose_name='datec')),
                ('numb', models.IntegerField(verbose_name='numb')),
                ('organization', models.CharField(max_length=256, verbose_name='organization')),
                ('replica', models.CharField(max_length=128, verbose_name='replica')),
                ('reg_number', models.CharField(max_length=64, verbose_name='reg_number')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='total')),
            ],
            options={
                'db_table': 'view_coming',
                'ordering': ['datec'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewOutgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateo', models.DateTimeField(verbose_name='dateo')),
                ('numb', models.IntegerField(verbose_name='numb')),
                ('organization', models.CharField(max_length=256, verbose_name='organization')),
                ('replica', models.CharField(max_length=128, verbose_name='replica')),
                ('reg_number', models.CharField(max_length=64, verbose_name='reg_number')),
                ('total', models.IntegerField(verbose_name='total')),
            ],
            options={
                'db_table': 'view_outgo',
                'ordering': ['dateo'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outgo_id', models.IntegerField(verbose_name='outgo_id')),
                ('dateo', models.DateTimeField(verbose_name='dateo')),
                ('numb', models.IntegerField(verbose_name='numb')),
                ('organization', models.CharField(max_length=256, verbose_name='organization')),
                ('replica', models.CharField(max_length=128, verbose_name='replica')),
                ('reg_number', models.CharField(max_length=64, verbose_name='reg_number')),
                ('catalog_id', models.IntegerField(verbose_name='catalog_id')),
                ('category', models.CharField(max_length=128, verbose_name='category_title')),
                ('title', models.CharField(max_length=255, verbose_name='catalog_title')),
                ('details', models.TextField(blank=True, null=True, verbose_name='catalog_details')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('unit', models.CharField(max_length=32, verbose_name='unit')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='catalog_photo')),
                ('storage', models.CharField(max_length=96, verbose_name='storage')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='total')),
            ],
            options={
                'db_table': 'view_sale',
                'ordering': ['outgo_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Automobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replica', models.CharField(max_length=128, verbose_name='replica')),
                ('reg_number', models.CharField(max_length=64, unique=True, verbose_name='reg_number')),
            ],
            options={
                'db_table': 'automobile',
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='catalog_title')),
                ('details', models.TextField(blank=True, null=True, verbose_name='catalog_details')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='catalog_price')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('unit', models.CharField(max_length=32, verbose_name='unit')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='catalog_photo')),
                ('storage', models.CharField(max_length=96, verbose_name='storage')),
            ],
            options={
                'db_table': 'catalog',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='category_title')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Coming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datec', models.DateTimeField(verbose_name='datec')),
                ('numb', models.IntegerField(verbose_name='numb')),
            ],
            options={
                'db_table': 'coming',
                'ordering': ['datec'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='full_name')),
                ('birthday', models.DateTimeField(verbose_name='birthday')),
                ('phone', models.CharField(max_length=64, verbose_name='phone')),
                ('category', models.CharField(max_length=128, verbose_name='category')),
            ],
            options={
                'db_table': 'driver',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='organization_name')),
                ('address', models.CharField(max_length=128, verbose_name='organization_address')),
                ('phone', models.CharField(max_length=32, verbose_name='organization_phone')),
                ('email', models.CharField(max_length=128, verbose_name='organization_email')),
                ('leader', models.CharField(max_length=128, verbose_name='organization_leader')),
            ],
            options={
                'db_table': 'organization',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Outgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateo', models.DateTimeField(verbose_name='dateo')),
                ('numb', models.IntegerField(verbose_name='numb')),
                ('automobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgo_automobile', to='stock.automobile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgo_organization', to='stock.organization')),
            ],
            options={
                'db_table': 'outgo',
                'ordering': ['dateo'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_catalog', to='stock.catalog')),
                ('outgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_outgo', to='stock.outgo')),
            ],
            options={
                'db_table': 'sale',
                'ordering': ['outgo'],
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['email'], name='organizatio_email_f97349_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name'], name='organizatio_name_bcc2ee_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['full_name'], name='driver_full_na_07a886_idx'),
        ),
        migrations.AddField(
            model_name='coming',
            name='automobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coming_automobile', to='stock.automobile'),
        ),
        migrations.AddField(
            model_name='coming',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coming_organization', to='stock.organization'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_category', to='stock.category'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='coming',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_coming', to='stock.coming'),
        ),
        migrations.AddField(
            model_name='automobile',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automobile_driver', to='stock.driver'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['outgo'], name='sale_outgo_i_ce5f86_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['catalog'], name='sale_catalog_6f4233_idx'),
        ),
        migrations.AddIndex(
            model_name='outgo',
            index=models.Index(fields=['dateo'], name='outgo_dateo_4b33f6_idx'),
        ),
        migrations.AddIndex(
            model_name='coming',
            index=models.Index(fields=['datec'], name='coming_datec_a205c8_idx'),
        ),
        migrations.AddIndex(
            model_name='catalog',
            index=models.Index(fields=['title'], name='catalog_title_a1bae3_idx'),
        ),
    ]
